### ISSUE TITLE
`flutter/flake.nix`: Unneeded scoping

### ISSUE THREAD

**Issue by cyntheticfox** [nix-community/templates#8]
For https://github.com/nix-community/templates/blob/main/flutter/flake.nix#L37-L38, `pkgs` scoping shouldn't be necessary since a `with` statement is used, right?

Moreover it just kinda contrasts with the line above it that doesn't scope...

**Comment by Mic92** [comment]
Addressed in https://github.com/nix-community/templates/pull/7/commits/808a48a1d90352df7a546d0ed89c5af70516e058
